# Generated by Django 4.1.9 on 2023-06-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_role', models.CharField(max_length=200)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
