# Generated by Django 4.1.9 on 2023-06-15 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='fooditem',
            name='menu_foodit_id_2de049_idx',
        ),
        migrations.RemoveIndex(
            model_name='fooditem',
            name='menu_foodit_name_cc8ea9_idx',
        ),
        migrations.RemoveIndex(
            model_name='fooditem',
            name='menu_foodit_created_637151_idx',
        ),
        migrations.RemoveIndex(
            model_name='menu',
            name='menu_menu_name_4933c0_idx',
        ),
        migrations.AddField(
            model_name='cart',
            name='food_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_cart', to='menu.fooditem'),
        ),
    ]
