# Generated by Django 4.1.9 on 2023-06-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='food_details',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='table_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
