# Generated by Django 4.1.9 on 2023-06-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_cart_remove_fooditem_menu_foodit_id_2de049_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
