# Generated by Django 4.1.9 on 2023-06-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_userdetails_food_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='order_status',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='user_email',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='contact_number',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
