# Generated by Django 4.1.9 on 2023-06-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_userdetails_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
