# Generated by Django 4.1.9 on 2023-07-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_userdetails_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='food_order_details',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
