# Generated by Django 4.1.9 on 2023-07-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_userdetails_food_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='serv_status',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
